-- Админ SMS 2FA (SCA, B-56). Idempotent.
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorCodeHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorExpiresAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorAttempts" INTEGER NOT NULL DEFAULT 0;
